interface Me {
  id: number;
  uid: string;
  email?: string;
  contact: string;
  first_name: string;
  last_name: string;
  profile_message: string;
  profile_image: string;
  profile_background: string;
  birth: string;
  recently_used_at?: string;
  video_able: number;
  call_able: number;
  remember_me_token?: string;
  official_account: number;
  created_at: Date | string;
  updated_at: Date | string;
  deleted_reason?: string;
  deleted_at?: Date | string;
  setting: {
    id: number;
    user_id: number;
    language: string;
    nt_preview: number;
    nt_group_chat: number;
    nt_inapp_noti: number;
    nt_inapp_sound: number;
    nt_inapp_vibrate: number;
    nt_disturb: number;
    nt_disturb_begin: Date | string;
    nt_disturb_end: Date | string;
    nt_market: number;
    nt_email: number;
    nt_sns_likes: number;
    nt_sns_comment: number;
    nt_sns_tag: number;
    nt_sns_followers: number;
    nt_sns_live: number;
    nt_sns_live_target: string;
    nt_sns_live_invitation: number;
    sc_recent_login: 'public' | 'friends' | 'private';
    sc_profile_photo: 'public' | 'friends' | 'private';
    sc_group_call: 'public' | 'friends' | 'private';
    sc_passcode_auth: number;
    sc_birthday_bound: number;
    sc_add_automatically: number;
    sc_biometric_auth: number;
    ct_active_chat: number;
    ct_word_suggestion: number;
    ct_chat_theme: string;
    ct_background_type: string;
    ct_background: string;
    ct_text_size: number;
    created_at: Date | string;
    updated_at: Date | string;
  };
}

export default Me;
